name: Readme CI
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
jobs:
  release:
    name: Update README
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update event summary
        uses: AnandChowdhary/events-summary@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: ":pencil: Generate README summary [skip ci]"
